export const paragraphsMain: string
export const paragraphsTitle: string
export const rightTip: string
export const collection: string
export const collections: string
export const smallCom: string
export const collectionSelect: string
export const mainTable: string
export const dragTitle: string
export const drag: string
export const littleCon: string
export const checkBoxGroup: string
export const bottom: string
export const timeGroup: string
export const inter: string
export const timeP: string
export const textBox: string
export const timeShow: string
export const dropDownMenu: string
export const radioGroupStyle: string
export const btn: string
export const gray: string
export const blue: string